version: "3.8"
services:
  sonarqube:
    image: docker.royfuwei.com/tools/ts-react-resume
    container_name: ts-resume-frontend
    restart: always
    networks:
      - devops

networks:
  devops:
    external: true